"""Knowledge unit & data-permission repository port (SPEC §9.1 KnowledgeRepository)."""

from abc import ABC, abstractmethod

from app.domain.models.entities import KnowledgeUnit, UnitPermission


class KnowledgeRepository(ABC):
    """Persistence port for knowledge_units / unit_permissions."""

    @abstractmethod
    def create_unit(self, unit: KnowledgeUnit) -> KnowledgeUnit:
        """Persist a new knowledge unit.

        Args:
            unit: Fully-populated ``KnowledgeUnit`` (id/created_at/updated_at
                are generated by the model defaults if unset).

        Returns:
            The persisted ``KnowledgeUnit`` with its ``id`` assigned.
        """

    @abstractmethod
    def update_unit(
        self,
        unit_id: str,
        *,
        title: str | None = None,
        content: str | None = None,
        summary: str | None = None,
        category: str | None = None,
        status: str | None = None,
        file_type: str | None = None,
        file_size: int | None = None,
        source_file_name: str | None = None,
    ) -> KnowledgeUnit | None:
        """Update editable unit fields; ``None`` means "leave unchanged".

        Editing overwrites ``content``/``updated_at`` (no version history,
        SPEC §2.2). Returns ``None`` when the unit does not exist.
        """

    @abstractmethod
    def soft_delete_units(self, unit_ids: list[str]) -> int:
        """Soft-delete units by setting ``status='offline'`` (SPEC §2.2).

        Args:
            unit_ids: Unit ids to offline.

        Returns:
            Number of rows updated.
        """

    @abstractmethod
    def list_units(
        self,
        *,
        title: str | None = None,
        category: str | None = None,
        status: str | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[KnowledgeUnit], int]:
        """Paginated unit list with optional filters.

        Returns:
            ``(items, total)`` ordered by ``created_at`` descending.
        """

    @abstractmethod
    def get_unit(self, unit_id: str) -> KnowledgeUnit | None:
        """Fetch a single unit by id (or ``None``)."""

    @abstractmethod
    def replace_unit_permissions(
        self, unit_id: str, permissions: list[tuple[str, str | None]]
    ) -> None:
        """Replace a unit's data permissions atomically (SPEC §3.2 transaction覆盖).

        Args:
            unit_id: Target unit id.
            permissions: Full list of ``(target_type, target_id)``. ``target_id``
                is ``None`` for ``global``.
        """

    @abstractmethod
    def get_unit_permissions(self, unit_id: str) -> list[UnitPermission]:
        """Return all data-permission rows for a unit."""
